### ISSUE TITLE
trying to build server

### ISSUE THREAD

**Issue by daniloab** [daniloab/finn#16]
- [ ] build the server from yarn server command
- [ ] understand how to build the other packages like we do inside entria

**Comment by daniloab** [comment]
error while running `yarn dev`

```bash
@finn/server:dev: $ yarn es ./src/index.ts
@finn/server:dev: $ node -r esbuild-register ./src/index.ts
@finn/server:dev: node:internal/modules/cjs/loader:936
@finn/server:dev:   throw err;
@finn/server:dev:   ^
@finn/server:dev: 
@finn/server:dev: Error: Cannot find module './dist/node'
@finn/server:dev: Require stack:
@finn/server:dev: - /Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/register.js
@finn/server:dev: - internal/preload
@finn/server:dev:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
@finn/server:dev:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@finn/server:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@finn/server:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@finn/server:dev:     at Object.<anonymous> (/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/register.js:1:1)
@finn/server:dev:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@finn/server:dev:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@finn/server:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
@finn/server:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@finn/server:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19) {
@finn/server:dev:   code: 'MODULE_NOT_FOUND',
@finn/server:dev:   requireStack: [
@finn/server:dev:     '/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/register.js',
@finn/server:dev:     'internal/preload'
@finn/server:dev:   ]
@finn/server:dev: }
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: Error: command finished with error: exit status 1
```

**Comment by daniloab** [comment]
after cleaning up the repo this is the actual error

```
@finn/server:dev: $ node -r esbuild-register ./src/index.ts
@finn/server:dev: /Users/daniloassis/Documents/projects/dab/finn/packages/graphql/src/node/typeRegister.ts:48
@finn/server:dev:   const { nodeField, nodesField, nodeInterface } = nodeDefinitions(
@finn/server:dev:                                                    ^
@finn/server:dev: 
@finn/server:dev: TypeError: (0 , import_graphql.nodeDefinitions) is not a function
@finn/server:dev:     at null.getTypeRegister (/Users/daniloassis/Documents/projects/dab/finn/packages/graphql/src/node/typeRegister.ts:48:52)
@finn/server:dev:     at Object.<anonymous> (/Users/daniloassis/Documents/projects/dab/finn/packages/modules/src/node/typeRegistry.ts:12:5)
@finn/server:dev:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@finn/server:dev:     at Module._compile (/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/dist/node.js:2258:26)
@finn/server:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@finn/server:dev:     at Object.newLoader [as .ts] (/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/dist/node.js:2262:9)
@finn/server:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
@finn/server:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@finn/server:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@finn/server:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: Error: command finished with error: exit status 1
```

**Comment by daniloab** [comment]
fix https://github.com/daniloab/finn/pull/25

it was an wrong import inside my monorepo
